### ISSUE TITLE
500 for Post /whitelist/cards/{token}

### ISSUE THREAD

**Issue by ikbened** [SpronQ/ncpa-api#6]
Posting a new card always results in a 500. My test output:

Request method:	POST
Request URI:	http://192.168.100.51:12800/api/tnm/v1/whitelist/cards/650e406?clientId=fee83c1a-0d3a-4bdd-9808-7fdcc5942720&label=Aap
Proxy:			<none>
Request params:	<none>
Query params:	clientId=fee83c1a-0d3a-4bdd-9808-7fdcc5942720
				label=Aap
Form params:	<none>
Path params:	token=650e406
Headers:		Authorization=Bearer eyJ0eX...
				Accept=*/*
				Content-Type=application/x-www-form-urlencoded; charset=ISO-8859-1
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
HTTP/1.1 500 Internal Server Error
Content-Type: application/xml
Date: Fri, 15 May 2020 09:45:20 GMT
Connection: close
Content-Length: 154

<apiResponseMessage>
  <message>Internal Server Error</message>
  <type>error</type>
</apiResponseMessage>

I get the same result in the ref api, although the response body differs:
{
  "message": "Could not find card",
  "name": "Error",
  "status": 500
}

What went wrong?

**Comment by jpwesselink** [comment]
I think a 404 error would be more appropriate here.

**Comment by ikbened** [comment]
> I think a 404 error would be more appropriate here.

I didn't expect an error at all....

**Comment by ikbened** [comment]
Wrong repo
